project_id = "nnrzsvtaeulxunxnbxtw"

[functions.send-team-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.get-booking]
verify_jwt = false
